# Generated by Django 4.1.5 on 2023-01-21 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import member.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('academic_qualification', models.CharField(choices=[('0', 'دكتوراه'), ('1', 'ماجستير'), ('2', 'بكالوريوس'), ('3', 'دبلوم'), ('4', 'ثانوي'), ('5', 'أساسي'), ('9', 'لايوجد')], max_length=1)),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
                ('major', models.CharField(blank=True, max_length=50, null=True)),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('street_address', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=20)),
                ('city', models.CharField(choices=[('Ambon', 'Ambon'), ('Balikpapan', 'Balikpapan'), ('Banda Aceh', 'Banda Aceh'), ('Bandar Lampung', 'Bandar Lampung'), ('Bandung', 'Bandung'), ('Banjar', 'Banjar'), ('Banjarbaru', 'Banjarbaru'), ('Banjarmasin', 'Banjarmasin'), ('Batam', 'Batam'), ('Batu', 'Batu'), ('Bau-Bau', 'Bau-Bau'), ('Bekasi', 'Bekasi'), ('Bengkulu', 'Bengkulu'), ('Bima', 'Bima'), ('Binjai', 'Binjai'), ('Bitung', 'Bitung'), ('Blitar', 'Blitar'), ('Bogor', 'Bogor'), ('Bontang', 'Bontang'), ('Bukittinggi', 'Bukittinggi'), ('Cilegon', 'Cilegon'), ('Cimahi', 'Cimahi'), ('Cirebon', 'Cirebon'), ('Denpasar', 'Denpasar'), ('Depok', 'Depok'), ('Dumai', 'Dumai'), ('Gorontalo', 'Gorontalo'), ('Gunungsitoli', 'Gunungsitoli'), ('Jakarta', 'Jakarta'), ('Jambi', 'Jambi'), ('Jayapura', 'Jayapura'), ('Kediri', 'Kediri'), ('Kendari', 'Kendari'), ('Kotamobagu', 'Kotamobagu'), ('Kupang', 'Kupang'), ('Langsa', 'Langsa'), ('Lhokseumawe', 'Lhokseumawe'), ('Lubuklinggau', 'Lubuklinggau'), ('Madiun', 'Madiun'), ('Magelang', 'Magelang'), ('Makassar', 'Makassar'), ('Malang', 'Malang'), ('Manado', 'Manado'), ('Mataram', 'Mataram'), ('Medan', 'Medan'), ('Metro', 'Metro'), ('Mojokerto City', 'Mojokerto City'), ('Padang', 'Padang'), ('Padang Panjang', 'Padang Panjang'), ('Padang Sidempuan', 'Padang Sidempuan'), ('Pagar Alam', 'Pagar Alam'), ('Palangka Raya', 'Palangka Raya'), ('Palembang', 'Palembang'), ('Palopo', 'Palopo'), ('Palu', 'Palu'), ('Pangkalpinang', 'Pangkalpinang'), ('Parepare', 'Parepare'), ('Pariaman', 'Pariaman'), ('Pasuruan', 'Pasuruan'), ('Payakumbuh', 'Payakumbuh'), ('Pekalongan', 'Pekalongan'), ('Pekanbaru', 'Pekanbaru'), ('Pematangsiantar', 'Pematangsiantar'), ('Pontianak', 'Pontianak'), ('Prabumulih', 'Prabumulih'), ('Probolinggo', 'Probolinggo'), ('Sabang', 'Sabang'), ('Salatiga', 'Salatiga'), ('Samarinda', 'Samarinda'), ('Sawahlunto', 'Sawahlunto'), ('Semarang', 'Semarang'), ('Serang', 'Serang'), ('Sibolga', 'Sibolga'), ('Singkawang', 'Singkawang'), ('Solok', 'Solok'), ('Sorong', 'Sorong'), ('South', 'South'), ('Subulussalam', 'Subulussalam'), ('Sukabumi', 'Sukabumi'), ('Sungai Penuh', 'Sungai Penuh'), ('Surabaya', 'Surabaya'), ('Surakarta', 'Surakarta'), ('Tangerang', 'Tangerang'), ('Tanjungbalai', 'Tanjungbalai'), ('Tanjungpinang', 'Tanjungpinang'), ('Tarakan', 'Tarakan'), ('Tasikmalaya', 'Tasikmalaya'), ('Tebing Tinggi', 'Tebing Tinggi'), ('Tegal', 'Tegal'), ('Ternate', 'Ternate'), ('Tidore', 'Tidore'), ('Tomohon', 'Tomohon'), ('Tual', 'Tual'), ('Yogyakarta', 'Yogyakarta')], max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyMembers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('family_name', models.CharField(max_length=15)),
                ('member_count', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('card_number', models.CharField(max_length=10, unique=True)),
                ('membership_type', models.CharField(choices=[('0', 'طالب'), ('1', 'مستثمر'), ('2', 'موضف')], max_length=1)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('expire_date', models.DateField()),
                ('membership_card', models.ImageField(blank=True, max_length=255, null=True, upload_to=member.models.membershipImagesDir)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('0', 'ذكر'), ('1', 'أنثى')], max_length=1)),
                ('place_of_birth', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('call_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(choices=[('0', 'طالب'), ('1', 'موظف'), ('2', 'مستثمر أو رجل أعمال'), ('3', 'غير ذلك'), ('4', 'لا يوجد')], max_length=20)),
                ('period_of_residence', models.CharField(choices=[('0', 'أقل من 6 شهور'), ('1', 'سنة أو أقل'), ('2', 'سنة إلى سنتين'), ('3', 'سنتين إلى 3 سنوات'), ('4', '3 سنوات إلى 4 سنوات'), ('5', '4 سنوات إلى 5 سنوات'), ('6', 'أكثر من 5 سنوات')], max_length=1)),
                ('photograph', models.ImageField(blank=True, max_length=255, null=True, upload_to=member.models.photographsDir)),
                ('passport_photo', models.ImageField(max_length=255, upload_to=member.models.passportDir)),
                ('residency_photo', models.ImageField(max_length=255, upload_to=member.models.residencyImagesDir)),
                ('passport_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_request_membership', models.BooleanField(default=False)),
                ('academic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.academic')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.address')),
                ('family_members', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.familymembers')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyMembersWife',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('family_members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.familymembers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyMembersChild',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('family_members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.familymembers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
