# Generated by Django 4.1.4 on 2022-12-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('academic_qualification', models.CharField(choices=[('0', 'دكتوراه'), ('1', 'ماجستير'), ('2', 'بكالوريوس'), ('3', 'دبلوم'), ('4', 'ثانوي'), ('5', 'أساسي'), ('9', 'لايوجد')], max_length=1)),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
                ('major', models.CharField(blank=True, max_length=50, null=True)),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
