# Generated by Django 4.1.4 on 2022-12-31 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('street_address', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('province', models.CharField(max_length=15)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyMembers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('family_name', models.CharField(max_length=15)),
                ('member_count', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('card_number', models.CharField(max_length=10, unique=True)),
                ('membership_type', models.CharField(choices=[('0', 'طالب'), ('1', 'مستثمر'), ('2', 'موضف')], max_length=1)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('expire_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('0', 'ذكر'), ('1', 'أنثى')], max_length=1)),
                ('place_of_birth', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('call_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('jop_title', models.CharField(max_length=20)),
                ('period_of_residence', models.CharField(choices=[('0', 'أقل من 6 شهور'), ('1', 'سنة أو أقل'), ('2', 'سنة إلى سنتين'), ('3', 'سنتين إلى 3 سنوات'), ('4', '3 سنوات إلى 4 سنوات'), ('5', '4 سنوات إلى 5 سنوات'), ('6', 'أكثر من 5 سنوات')], max_length=1)),
                ('photograph', models.ImageField(upload_to='documents/images/photographs')),
                ('passport_photo', models.ImageField(upload_to='documents/images/passportImages')),
                ('residency_photo', models.ImageField(upload_to='documents/images/residencyImages')),
                ('academic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.academic')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.address')),
                ('family_members', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.familymembers')),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyMembersWife',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('family_members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.familymembers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyMembersChild',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('family_members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.familymembers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
