# Generated by Django 4.1.5 on 2023-01-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Ambon', 'Ambon'), ('Balikpapan', 'Balikpapan'), ('Banda Aceh', 'Banda Aceh'), ('Bandar Lampung', 'Bandar Lampung'), ('Bandung', 'Bandung'), ('Banjar', 'Banjar'), ('Banjarbaru', 'Banjarbaru'), ('Banjarmasin', 'Banjarmasin'), ('Batam', 'Batam'), ('Batu', 'Batu'), ('Bau-Bau', 'Bau-Bau'), ('Bekasi', 'Bekasi'), ('Bengkulu', 'Bengkulu'), ('Bima', 'Bima'), ('Binjai', 'Binjai'), ('Bitung', 'Bitung'), ('Blitar', 'Blitar'), ('Bogor', 'Bogor'), ('Bontang', 'Bontang'), ('Bukittinggi', 'Bukittinggi'), ('Cilegon', 'Cilegon'), ('Cimahi', 'Cimahi'), ('Cirebon', 'Cirebon'), ('Denpasar', 'Denpasar'), ('Depok', 'Depok'), ('Dumai', 'Dumai'), ('Gorontalo', 'Gorontalo'), ('Gunungsitoli', 'Gunungsitoli'), ('Jakarta', 'Jakarta'), ('Jambi', 'Jambi'), ('Jayapura', 'Jayapura'), ('Kediri', 'Kediri'), ('Kendari', 'Kendari'), ('Kotamobagu', 'Kotamobagu'), ('Kupang', 'Kupang'), ('Langsa', 'Langsa'), ('Lhokseumawe', 'Lhokseumawe'), ('Lubuklinggau', 'Lubuklinggau'), ('Madiun', 'Madiun'), ('Magelang', 'Magelang'), ('Makassar', 'Makassar'), ('Malang', 'Malang'), ('Manado', 'Manado'), ('Mataram', 'Mataram'), ('Medan', 'Medan'), ('Metro', 'Metro'), ('Mojokerto City', 'Mojokerto City'), ('Padang', 'Padang'), ('Padang Panjang', 'Padang Panjang'), ('Padang Sidempuan', 'Padang Sidempuan'), ('Pagar Alam', 'Pagar Alam'), ('Palangka Raya', 'Palangka Raya'), ('Palembang', 'Palembang'), ('Palopo', 'Palopo'), ('Palu', 'Palu'), ('Pangkalpinang', 'Pangkalpinang'), ('Parepare', 'Parepare'), ('Pariaman', 'Pariaman'), ('Pasuruan', 'Pasuruan'), ('Payakumbuh', 'Payakumbuh'), ('Pekalongan', 'Pekalongan'), ('Pekanbaru', 'Pekanbaru'), ('Pematangsiantar', 'Pematangsiantar'), ('Pontianak', 'Pontianak'), ('Prabumulih', 'Prabumulih'), ('Probolinggo', 'Probolinggo'), ('Sabang', 'Sabang'), ('Salatiga', 'Salatiga'), ('Samarinda', 'Samarinda'), ('Sawahlunto', 'Sawahlunto'), ('Semarang', 'Semarang'), ('Serang', 'Serang'), ('Sibolga', 'Sibolga'), ('Singkawang', 'Singkawang'), ('Solok', 'Solok'), ('Sorong', 'Sorong'), ('South', 'South'), ('Subulussalam', 'Subulussalam'), ('Sukabumi', 'Sukabumi'), ('Sungai Penuh', 'Sungai Penuh'), ('Surabaya', 'Surabaya'), ('Surakarta', 'Surakarta'), ('Tangerang', 'Tangerang'), ('Tanjungbalai', 'Tanjungbalai'), ('Tanjungpinang', 'Tanjungpinang'), ('Tarakan', 'Tarakan'), ('Tasikmalaya', 'Tasikmalaya'), ('Tebing Tinggi', 'Tebing Tinggi'), ('Tegal', 'Tegal'), ('Ternate', 'Ternate'), ('Tidore', 'Tidore'), ('Tomohon', 'Tomohon'), ('Tual', 'Tual'), ('Yogyakarta', 'Yogyakarta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=20),
        ),
    ]
