# Generated by Django 4.1.5 on 2023-01-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_address_city_alter_address_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='job_title',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20),
        ),
    ]
