# Generated by Django 4.1.4 on 2023-01-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_address_familymembers_membership_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photograph',
            field=models.ImageField(null=True, upload_to='documents/images/photographs'),
        ),
    ]
