# Generated by Django 4.1.5 on 2023-01-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_person_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='job_title',
            field=models.CharField(choices=[('0', 'طالب'), ('1', 'موظف'), ('2', 'مستثمر أو رجل أعمال'), ('3', 'غير ذلك'), ('4', 'لا يوجد')], max_length=20),
        ),
    ]
