# Generated by Django 4.1.4 on 2023-01-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_person_photograph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photograph',
            field=models.ImageField(null=True, upload_to='documents/images/photographs'),
        ),
    ]
