# Generated by Django 4.1.5 on 2023-01-11 14:13

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_person_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membership_card',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=member.models.membershipImagesDir),
        ),
    ]
