# Generated by Django 4.1.4 on 2023-01-01 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0005_alter_person_photograph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='academic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.academic'),
        ),
        migrations.AlterField(
            model_name='person',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.familymembers'),
        ),
        migrations.AlterField(
            model_name='person',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.membership'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='documents/images/photographs'),
        ),
    ]
