# Generated by Django 4.1.4 on 2023-01-01 17:19

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_person_academic_alter_person_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='passport_photo',
            field=models.ImageField(upload_to=member.models.UploadToPathAndRename(
                'D:\\Mohammed\\Projects\\YemeniCommunityIndonesia\\src\\media\\documents/images/passportImages')),
        ),
        migrations.AlterField(
            model_name='person',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to=member.models.UploadToPathAndRename(
                'D:\\Mohammed\\Projects\\YemeniCommunityIndonesia\\src\\media\\documents/images/photographs')),
        ),
        migrations.AlterField(
            model_name='person',
            name='residency_photo',
            field=models.ImageField(upload_to=member.models.UploadToPathAndRename(
                'D:\\Mohammed\\Projects\\YemeniCommunityIndonesia\\src\\media\\documents/images/residencyImages')),
        ),
    ]
