# Generated by Django 4.1.4 on 2023-01-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_person_passport_photo_alter_person_photograph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='passport_photo',
            field=models.ImageField(upload_to='documents/images/passportImages'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='documents/images/photographs'),
        ),
        migrations.AlterField(
            model_name='person',
            name='residency_photo',
            field=models.ImageField(upload_to='documents/images/residencyImages'),
        ),
    ]
