# Generated by Django 4.1.4 on 2023-01-01 17:37

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_alter_person_passport_photo_alter_person_photograph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='passport_photo',
            field=models.ImageField(upload_to=member.models.PASSPORTS_DIR),
        ),
        migrations.AlterField(
            model_name='person',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to=member.models.PHOTOGRAPHS_DIR),
        ),
        migrations.AlterField(
            model_name='person',
            name='residency_photo',
            field=models.ImageField(upload_to=member.models.RESIDENCY_IMAGES_DIR),
        ),
    ]
