# Generated by Django 4.1.4 on 2023-01-01 17:46

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_alter_person_passport_photo_alter_person_photograph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='passport_photo',
            field=models.ImageField(max_length=255, upload_to=member.models.passportDir),
        ),
        migrations.AlterField(
            model_name='person',
            name='photograph',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=member.models.photographsDir),
        ),
        migrations.AlterField(
            model_name='person',
            name='residency_photo',
            field=models.ImageField(max_length=255, upload_to=member.models.residencyImagesDir),
        ),
    ]
