# Generated by Django 4.1.4 on 2023-01-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_alter_person_passport_photo_alter_person_photograph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_request_membership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
