# Generated by Django 4.1.4 on 2023-01-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_person_is_request_membership_person_is_validated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='jop_title',
            new_name='job_title',
        ),
    ]
