# Generated by Django 4.1.5 on 2023-01-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_agent', models.CharField(blank=True, max_length=256, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('action', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=1)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockedClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_agent', models.CharField(blank=True, max_length=256, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('block_type', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=1)),
                ('blocked_times', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_column='name', editable=False, max_length=50)),
                ('value', models.CharField(db_column='value', max_length=50)),
                ('access_type', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], db_column='access_type', default='0', editable=False, max_length=1)),
                ('parameter_type', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], db_column='parameter_type', default='0', editable=False, max_length=1)),
                ('description', models.CharField(blank=True, db_column='description', editable=False, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
