# Generated by Django 4.1.4 on 2022-12-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_agent', models.CharField(blank=True, max_length=256, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('action', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockedClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_agent', models.CharField(blank=True, max_length=256, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('block_type', models.CharField(choices=[('Unblocked', 'Unblocked'), ('Temporary', 'Temporary'), ('Indefinitely', 'Indefinitely')], max_length=20)),
                ('blocked_times', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_column='name', editable=False, max_length=50)),
                ('value', models.CharField(db_column='value', max_length=50)),
                ('description', models.CharField(blank=True, db_column='description', editable=False, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
