# Generated by Django 4.1.4 on 2022-12-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='access_type',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], db_column='access_type', default='0', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='parameter',
            name='parameter_type',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], db_column='parameter_type', default='0', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
