# Generated by Django 4.1.4 on 2022-12-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_parameter_access_type_parameter_parameter_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedclient',
            name='block_type',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=1),
        ),
    ]
